---
plugins:
  eslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - "javascript"
exclude_patterns:
  - tests.js
  - tests/
  - .editorconfig
  - .esformatter
  - .eslintrc.json
  - .travis.yml
