---
version: 2
plugins:
  eslint:
    enabled: true
    config: .eslintrc
  duplication:
    enabled: true
    config:
      config: .eslintrc
      languages:
      - javascript:
exclude_patterns:
- "**/node_modules/**/*"
- tests/
- .editorconfig
- .esformatter
- .eslintrc.json
- .travis.yml
